[package]
name = "powerline-rs"
description = "powerline-shell rewritten in Rust. Inspired by powerline-go."
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]

[dependencies]
clap  = "2.27"
git2  = { version = "0.6", optional = true }
flame = { version = "0.2", optional = true }

[features]
default = ["git2"]
